import os
from unittest import TestCase

from eventsourcing.system import SingleThreadedRunner

from dogschool_es.aggregates.trick_aggregate import Trick
from dogschool_es.application import DogSchool
from dogschool_es.tricks_processapp import Tricks
from dogschool_es.system import dog_system
from dogschool_es.tricks_readmodel_processapp import TricksReadModel


class TestSystem(TestCase):
    def test_system_dog_events_stored(self) -> None:
        """
        Test the system with the dog events stored in the on-disk database
        (dogschool_es_mockDB2dogs3tricks.sqlite).
        The Tricks Process Application should be able to process the Dog events
        and as a sideeffect of the Dog.TrickAdded event create the Trick.DogAdded event.
        The Tricks Read Model Process Application should get triggered to process the Trick.DogAdded event.
        """
        
        os.environ["PERSISTENCE_MODULE"] = "eventsourcing.sqlite"
        os.environ["SQLITE_DBNAME"] = "dogschool_es_mockDB2dogs3tricks.sqlite"        

        runner = SingleThreadedRunner(dog_system)
        runner.start()
        
        
        # Get the application objects.
        school = runner.get(DogSchool)
        tricks = runner.get(Tricks)
        tricks_readmodel = runner.get(TricksReadModel)
        
        # Enable when rebuild from stored events.
        tricks.pull_and_process(leader_name=DogSchool.__name__, start=1) # start from the beginning!
        
        trick = tricks.get_trick('roll over')
        assert isinstance(trick, Trick)
        assert trick.dog_names == ["Fido", "Buster"]
        
        trick2 = tricks.get_trick('play dead')
        assert trick2.dog_names == ["Fido"]
                
        assert tricks_readmodel.amount_events_processed == 3
        

        # Stop the runner.
        runner.stop()
        
    def test_system_dog_events_and_tricks_events_stored(self) -> None:
        """
        Test the system with the dog events AND the tricks events generated by the system
        as a sideeffect from the dog events stored in the on-disk database
        (dogschool_es_mockDB2dogs3tricks_and_tricksevents.sqlite).

        The Tricks Read Model Process Application should replay the events from the Tricks domain
        from the beginning, and process the Trick.DogAdded events.
        """
        
        os.environ["PERSISTENCE_MODULE"] = "eventsourcing.sqlite"
        os.environ["SQLITE_DBNAME"] = "dogschool_es_mockDB2dogs3tricks_and_tricksevents.sqlite"        

        runner = SingleThreadedRunner(dog_system)
        runner.start()
        
        # test projection is empty? integration test
        
        
        # Get the application objects.
        tricks = runner.get(Tricks)
        tricks_readmodel = runner.get(TricksReadModel)
        
        trick = tricks.get_trick('roll over')
        assert isinstance(trick, Trick)
        assert trick.dog_names == ["Fido", "Buster"]
        
        trick2 = tricks.get_trick('play dead')
        assert trick2.dog_names == ["Fido"]
                
        tricks_readmodel.pull_and_process(leader_name=Tricks.__name__, start=1) # start from the beginning!
        assert tricks_readmodel.amount_events_processed == 3
        

        # Stop the runner.
        runner.stop()        